{
  "tool": "sopa",
  "scan_timestamp": "2025-10-06T02:56:22Z",
  "workflow_run_id": "18268674820",
  "versions": {
    "2.0.3--pyhdfd78af_0": {
      "image": "ghcr.io/bundlecore/products/bfx/sopa:2.0.3--pyhdfd78af_0",
      "vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2025-47273",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python3.12/site-packages/setuptools-75.8.2-py3.9.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@75.8.2",
            "UID": "8723eac1db2ae344"
          },
          "InstalledVersion": "75.8.2",
          "FixedVersion": "78.1.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:005eab7827da12a4bbc29083e543fd151d9c238a0c076481df10d2937c6c8cb7",
            "DiffID": "sha256:5aaf1e046ad57b53a338e4c735b31e65e64bcbe305bf0ec0c2a9e0c73b4f7937"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47273",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "setuptools: Path Traversal Vulnerability in setuptools PackageIndex",
          "Description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
              "V3Score": 7.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:13578",
            "https://access.redhat.com/security/cve/CVE-2025-47273",
            "https://bugzilla.redhat.com/2366982",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2366982",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-47273",
            "https://errata.almalinux.org/9/ALSA-2025-13578.html",
            "https://errata.rockylinux.org/RLSA-2025:11036",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2025-49.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88",
            "https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b",
            "https://github.com/pypa/setuptools/issues/4946",
            "https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf",
            "https://linux.oracle.com/cve/CVE-2025-47273.html",
            "https://linux.oracle.com/errata/ELSA-2025-9940.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47273",
            "https://ubuntu.com/security/notices/USN-7544-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47273"
          ],
          "PublishedDate": "2025-05-17T16:15:19.11Z",
          "LastModifiedDate": "2025-06-12T16:29:01.66Z"
        },
        {
          "VulnerabilityID": "CVE-2025-47287",
          "PkgName": "tornado",
          "PkgPath": "usr/local/lib/python3.12/site-packages/tornado-6.4.2.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/tornado@6.4.2",
            "UID": "efb5de2a12e47f46"
          },
          "InstalledVersion": "6.4.2",
          "FixedVersion": "6.5",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:005eab7827da12a4bbc29083e543fd151d9c238a0c076481df10d2937c6c8cb7",
            "DiffID": "sha256:5aaf1e046ad57b53a338e4c735b31e65e64bcbe305bf0ec0c2a9e0c73b4f7937"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47287",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "tornado: Tornado Multipart Form-Data Denial of Service",
          "Description": "Tornado is a Python web framework and asynchronous networking library. When Tornado's ``multipart/form-data`` parser encounters certain errors, it logs a warning but continues trying to parse the remainder of the data. This allows remote attackers to generate an extremely high volume of logs, constituting a DoS attack. This DoS is compounded by the fact that the logging subsystem is synchronous. All versions of Tornado prior to 6.5.0 are affected. The vulnerable parser is enabled by default. Upgrade to Tornado version 6.50 to receive a patch. As a workaround, risk can be mitigated by blocking `Content-Type: multipart/form-data` in a proxy.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-770"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 2,
            "ghsa": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:8136",
            "https://access.redhat.com/security/cve/CVE-2025-47287",
            "https://bugzilla.redhat.com/2366703",
            "https://errata.almalinux.org/9/ALSA-2025-8136.html",
            "https://github.com/tornadoweb/tornado",
            "https://github.com/tornadoweb/tornado/commit/b39b892bf78fe8fea01dd45199aa88307e7162f3",
            "https://github.com/tornadoweb/tornado/security/advisories/GHSA-7cx3-6m66-7c5m",
            "https://linux.oracle.com/cve/CVE-2025-47287.html",
            "https://linux.oracle.com/errata/ELSA-2025-8664.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00038.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47287",
            "https://ubuntu.com/security/notices/USN-7547-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47287"
          ],
          "PublishedDate": "2025-05-15T22:15:18.827Z",
          "LastModifiedDate": "2025-05-29T06:15:23.09Z"
        }
      ],
      "vulnerability_count": 2
    },
    "2.1.0--pyhdfd78af_0": {
      "image": "ghcr.io/bundlecore/products/bfx/sopa:2.1.0--pyhdfd78af_0",
      "vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2025-48379",
          "PkgName": "pillow",
          "PkgPath": "usr/local/lib/python3.12/site-packages/pillow-11.2.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pillow@11.2.1",
            "UID": "5d73940db83ed6d2"
          },
          "InstalledVersion": "11.2.1",
          "FixedVersion": "11.3.0",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:24861b1cbfa3f3d22ace9e54e68ece22e141225d7e18499cf289244d7fd0566c",
            "DiffID": "sha256:f6aaa51e655b4ba9079cee77531a5b5548c8a67b55519f281e40164d0ba5e172"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-48379",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pillow: pillow: Pillow DDS Heap Buffer Overflow",
          "Description": "Pillow is a Python imaging library. In versions 11.2.0 to before 11.3.0, there is a heap buffer overflow when writing a sufficiently large (>64k encoded with default settings) image in the DDS format due to writing into a buffer without checking for available space. This only affects users who save untrusted data as a compressed DDS image. This issue has been patched in version 11.3.0.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-122"
          ],
          "VendorSeverity": {
            "bitnami": 3,
            "ghsa": 3,
            "redhat": 3
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 7.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 7.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 7.1
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-48379",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2025-61.yaml",
            "https://github.com/python-pillow/Pillow",
            "https://github.com/python-pillow/Pillow/commit/ef98b3510e3e4f14b547762764813d7e5ca3c5a4",
            "https://github.com/python-pillow/Pillow/pull/9041",
            "https://github.com/python-pillow/Pillow/releases/tag/11.3.0",
            "https://github.com/python-pillow/Pillow/security/advisories/GHSA-xg8h-j46f-w952",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-48379",
            "https://www.cve.org/CVERecord?id=CVE-2025-48379"
          ],
          "PublishedDate": "2025-07-01T19:15:27.353Z",
          "LastModifiedDate": "2025-07-03T15:14:12.767Z"
        }
      ],
      "vulnerability_count": 1
    },
    "2.1.3--pyhdfd78af_0": {
      "image": "ghcr.io/bundlecore/products/bfx/sopa:2.1.3--pyhdfd78af_0",
      "vulnerabilities": [],
      "vulnerability_count": 0
    }
  },
  "summary": {
    "total_versions_scanned": 3,
    "total_vulnerabilities": 3
  }
}
