{
  "tool": "strelka2",
  "scan_timestamp": "2025-10-06T17:39:21Z",
  "workflow_run_id": "18289448834",
  "versions": {
    "2.7.1--py27_0": {
      "image": "ghcr.io/bundlecore/products/bfx/strelka2:2.7.1--py27_0",
      "vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2023-37920",
          "PkgName": "certifi",
          "PkgPath": "usr/local/lib/python2.7/site-packages/certifi-2017.01.23-py2.7.egg-info",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/certifi@2017.01.23",
            "UID": "352fdcfa758fb839"
          },
          "InstalledVersion": "2017.01.23",
          "FixedVersion": "2023.7.22",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-37920",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: Removal of e-Tugra root certificate",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-345"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 4,
            "ghsa": 3,
            "nvd": 4,
            "oracle-oval": 2,
            "photon": 4,
            "redhat": 1
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:7753",
            "https://access.redhat.com/security/cve/CVE-2023-37920",
            "https://bugzilla.redhat.com/2226586",
            "https://bugzilla.redhat.com/2242493",
            "https://errata.almalinux.org/9/ALSA-2023-7753.html",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A",
            "https://linux.oracle.com/cve/CVE-2023-37920.html",
            "https://linux.oracle.com/errata/ELSA-2024-0133.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-37920",
            "https://security.netapp.com/advisory/ntap-20240912-0002",
            "https://security.netapp.com/advisory/ntap-20240912-0002/",
            "https://www.cve.org/CVERecord?id=CVE-2023-37920"
          ],
          "PublishedDate": "2023-07-25T21:15:10.827Z",
          "LastModifiedDate": "2025-02-13T13:50:15.813Z"
        },
        {
          "VulnerabilityID": "CVE-2019-20916",
          "PkgName": "pip",
          "PkgPath": "usr/local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@9.0.1",
            "UID": "ff35bb2883372a0a"
          },
          "InstalledVersion": "9.0.1",
          "FixedVersion": "19.2",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-20916",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pip: directory traversal in _download_http_url() function in src/pip/_internal/download.py",
          "Description": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8
            }
          },
          "References": [
            "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html",
            "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html",
            "https://access.redhat.com/security/cve/CVE-2019-20916",
            "https://errata.almalinux.org/8/ALSA-2020-4654.html",
            "https://github.com/advisories/GHSA-gpvv-69j7-gwj8",
            "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2020-173.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace (19.2)",
            "https://github.com/pypa/pip/compare/19.1.1...19.2",
            "https://github.com/pypa/pip/issues/6413",
            "https://linux.oracle.com/cve/CVE-2019-20916.html",
            "https://linux.oracle.com/errata/ELSA-2022-9204.html",
            "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-20916",
            "https://ubuntu.com/security/notices/USN-4601-1",
            "https://www.cve.org/CVERecord?id=CVE-2019-20916",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2020-09-04T20:15:11.013Z",
          "LastModifiedDate": "2024-11-21T04:39:40.913Z"
        },
        {
          "VulnerabilityID": "CVE-2021-3572",
          "PkgName": "pip",
          "PkgPath": "usr/local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@9.0.1",
            "UID": "ff35bb2883372a0a"
          },
          "InstalledVersion": "9.0.1",
          "FixedVersion": "21.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3572",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pip: Incorrect handling of unicode separators in git references",
          "Description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 1,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 3,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V2Score": 3.5,
              "V3Score": 5.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 4.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2021:3254",
            "https://access.redhat.com/security/cve/CVE-2021-3572",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1962856",
            "https://github.com/advisories/GHSA-5xp3-jfq3-5q8x",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2021-437.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b",
            "https://github.com/pypa/pip/issues/10042",
            "https://github.com/pypa/pip/issues/10042#issuecomment-857452480",
            "https://github.com/pypa/pip/pull/9827",
            "https://github.com/skazi0/CVE-2021-3572/blob/master/CVE-2021-3572-v9.0.1.patch",
            "https://linux.oracle.com/cve/CVE-2021-3572.html",
            "https://linux.oracle.com/errata/ELSA-2023-12349.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-3572",
            "https://packetstormsecurity.com/files/162712/USN-4961-1.txt",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://ubuntu.com/security/notices/USN-4961-2",
            "https://www.cve.org/CVERecord?id=CVE-2021-3572",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-11-10T18:15:09.51Z",
          "LastModifiedDate": "2024-11-21T06:21:52.473Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40897",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-33.1.0.post20170122-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@33.1.0.post20170122",
            "UID": "306670c0b8d1253c"
          },
          "InstalledVersion": "33.1.0.post20170122",
          "FixedVersion": "65.5.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40897",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
          "Description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-1333"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:0952",
            "https://access.redhat.com/security/cve/CVE-2022-40897",
            "https://bugzilla.redhat.com/2158559",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2158559",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897",
            "https://errata.almalinux.org/9/ALSA-2023-0952.html",
            "https://errata.rockylinux.org/RLSA-2023:0952",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2022-43012.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
            "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
            "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
            "https://github.com/pypa/setuptools/issues/3659",
            "https://linux.oracle.com/cve/CVE-2022-40897.html",
            "https://linux.oracle.com/errata/ELSA-2024-2987.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
            "https://security.netapp.com/advisory/ntap-20230214-0001",
            "https://security.netapp.com/advisory/ntap-20230214-0001/",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://setuptools.pypa.io/en/latest",
            "https://ubuntu.com/security/notices/USN-5817-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-40897"
          ],
          "PublishedDate": "2022-12-23T00:15:13.987Z",
          "LastModifiedDate": "2024-11-21T07:22:13.787Z"
        },
        {
          "VulnerabilityID": "CVE-2024-6345",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-33.1.0.post20170122-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@33.1.0.post20170122",
            "UID": "306670c0b8d1253c"
          },
          "InstalledVersion": "33.1.0.post20170122",
          "FixedVersion": "70.0.0",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-6345",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa/setuptools: Remote code execution via download functions in the package_index module in pypa/setuptools",
          "Description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-94"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:6726",
            "https://access.redhat.com/security/cve/CVE-2024-6345",
            "https://bugzilla.redhat.com/2297771",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2297771",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-6345",
            "https://errata.almalinux.org/9/ALSA-2024-6726.html",
            "https://errata.rockylinux.org/RLSA-2024:6726",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0",
            "https://github.com/pypa/setuptools/pull/4332",
            "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5",
            "https://linux.oracle.com/cve/CVE-2024-6345.html",
            "https://linux.oracle.com/errata/ELSA-2024-6726.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
            "https://ubuntu.com/security/notices/USN-7002-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-6345"
          ],
          "PublishedDate": "2024-07-15T01:15:01.73Z",
          "LastModifiedDate": "2024-11-21T09:49:28.17Z"
        },
        {
          "VulnerabilityID": "CVE-2025-47273",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-33.1.0.post20170122-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@33.1.0.post20170122",
            "UID": "306670c0b8d1253c"
          },
          "InstalledVersion": "33.1.0.post20170122",
          "FixedVersion": "78.1.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47273",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "setuptools: Path Traversal Vulnerability in setuptools PackageIndex",
          "Description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
              "V3Score": 7.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:13578",
            "https://access.redhat.com/security/cve/CVE-2025-47273",
            "https://bugzilla.redhat.com/2366982",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2366982",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-47273",
            "https://errata.almalinux.org/9/ALSA-2025-13578.html",
            "https://errata.rockylinux.org/RLSA-2025:11036",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2025-49.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88",
            "https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b",
            "https://github.com/pypa/setuptools/issues/4946",
            "https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf",
            "https://linux.oracle.com/cve/CVE-2025-47273.html",
            "https://linux.oracle.com/errata/ELSA-2025-9940.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47273",
            "https://ubuntu.com/security/notices/USN-7544-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47273"
          ],
          "PublishedDate": "2025-05-17T16:15:19.11Z",
          "LastModifiedDate": "2025-06-12T16:29:01.66Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40898",
          "PkgName": "wheel",
          "PkgPath": "usr/local/lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/wheel@0.29.0",
            "UID": "4b943d57647bd1d1"
          },
          "InstalledVersion": "0.29.0",
          "FixedVersion": "0.38.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:a5ffb414f5054115748a020f7f319a7aa892a07cfac343c33b859febca753346",
            "DiffID": "sha256:8e2039ddc17ba1f5c72f2dd9452da7eb9ab1d1d1bf516208db9261aa0993f49b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40898",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
          "Description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:6712",
            "https://access.redhat.com/security/cve/CVE-2022-40898",
            "https://bugzilla.redhat.com/2165864",
            "https://errata.almalinux.org/9/ALSA-2023-6712.html",
            "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6",
            "https://github.com/pypa/advisory-database/tree/main/vulns/wheel/PYSEC-2022-43017.yaml",
            "https://github.com/pypa/wheel",
            "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
            "https://github.com/pypa/wheel/commit/88f02bc335d5404991e532e7f3b0fc80437bf4e0",
            "https://linux.oracle.com/cve/CVE-2022-40898.html",
            "https://linux.oracle.com/errata/ELSA-2023-6712.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
            "https://pypi.org/project/wheel",
            "https://pypi.org/project/wheel/",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40898/51499",
            "https://ubuntu.com/security/notices/USN-5821-1",
            "https://ubuntu.com/security/notices/USN-5821-2",
            "https://ubuntu.com/security/notices/USN-5821-3",
            "https://www.cve.org/CVERecord?id=CVE-2022-40898"
          ],
          "PublishedDate": "2022-12-23T00:15:14.043Z",
          "LastModifiedDate": "2025-04-15T16:15:19.237Z"
        }
      ],
      "vulnerability_count": 7
    },
    "2.9.7--0": {
      "image": "ghcr.io/bundlecore/products/bfx/strelka2:2.9.7--0",
      "vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2023-37920",
          "PkgName": "certifi",
          "PkgPath": "usr/local/lib/python2.7/site-packages/certifi-2018.08.13-py2.7.egg-info",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/certifi@2018.08.13",
            "UID": "275329dd4304ae0c"
          },
          "InstalledVersion": "2018.08.13",
          "FixedVersion": "2023.7.22",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-37920",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: Removal of e-Tugra root certificate",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-345"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 4,
            "ghsa": 3,
            "nvd": 4,
            "oracle-oval": 2,
            "photon": 4,
            "redhat": 1
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:7753",
            "https://access.redhat.com/security/cve/CVE-2023-37920",
            "https://bugzilla.redhat.com/2226586",
            "https://bugzilla.redhat.com/2242493",
            "https://errata.almalinux.org/9/ALSA-2023-7753.html",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A",
            "https://linux.oracle.com/cve/CVE-2023-37920.html",
            "https://linux.oracle.com/errata/ELSA-2024-0133.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-37920",
            "https://security.netapp.com/advisory/ntap-20240912-0002",
            "https://security.netapp.com/advisory/ntap-20240912-0002/",
            "https://www.cve.org/CVERecord?id=CVE-2023-37920"
          ],
          "PublishedDate": "2023-07-25T21:15:10.827Z",
          "LastModifiedDate": "2025-02-13T13:50:15.813Z"
        },
        {
          "VulnerabilityID": "CVE-2019-20916",
          "PkgName": "pip",
          "PkgPath": "usr/local/lib/python2.7/site-packages/pip-18.0-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@18.0",
            "UID": "7ea6a41045e479aa"
          },
          "InstalledVersion": "18.0",
          "FixedVersion": "19.2",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-20916",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pip: directory traversal in _download_http_url() function in src/pip/_internal/download.py",
          "Description": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8
            }
          },
          "References": [
            "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html",
            "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html",
            "https://access.redhat.com/security/cve/CVE-2019-20916",
            "https://errata.almalinux.org/8/ALSA-2020-4654.html",
            "https://github.com/advisories/GHSA-gpvv-69j7-gwj8",
            "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2020-173.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace (19.2)",
            "https://github.com/pypa/pip/compare/19.1.1...19.2",
            "https://github.com/pypa/pip/issues/6413",
            "https://linux.oracle.com/cve/CVE-2019-20916.html",
            "https://linux.oracle.com/errata/ELSA-2022-9204.html",
            "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-20916",
            "https://ubuntu.com/security/notices/USN-4601-1",
            "https://www.cve.org/CVERecord?id=CVE-2019-20916",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2020-09-04T20:15:11.013Z",
          "LastModifiedDate": "2024-11-21T04:39:40.913Z"
        },
        {
          "VulnerabilityID": "CVE-2021-3572",
          "PkgName": "pip",
          "PkgPath": "usr/local/lib/python2.7/site-packages/pip-18.0-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@18.0",
            "UID": "7ea6a41045e479aa"
          },
          "InstalledVersion": "18.0",
          "FixedVersion": "21.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3572",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pip: Incorrect handling of unicode separators in git references",
          "Description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 1,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 3,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V2Score": 3.5,
              "V3Score": 5.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 4.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2021:3254",
            "https://access.redhat.com/security/cve/CVE-2021-3572",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1962856",
            "https://github.com/advisories/GHSA-5xp3-jfq3-5q8x",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2021-437.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b",
            "https://github.com/pypa/pip/issues/10042",
            "https://github.com/pypa/pip/issues/10042#issuecomment-857452480",
            "https://github.com/pypa/pip/pull/9827",
            "https://github.com/skazi0/CVE-2021-3572/blob/master/CVE-2021-3572-v9.0.1.patch",
            "https://linux.oracle.com/cve/CVE-2021-3572.html",
            "https://linux.oracle.com/errata/ELSA-2023-12349.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-3572",
            "https://packetstormsecurity.com/files/162712/USN-4961-1.txt",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://ubuntu.com/security/notices/USN-4961-2",
            "https://www.cve.org/CVERecord?id=CVE-2021-3572",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-11-10T18:15:09.51Z",
          "LastModifiedDate": "2024-11-21T06:21:52.473Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40897",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-40.0.0-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@40.0.0",
            "UID": "40194c84ee4b8bf6"
          },
          "InstalledVersion": "40.0.0",
          "FixedVersion": "65.5.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40897",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
          "Description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-1333"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:0952",
            "https://access.redhat.com/security/cve/CVE-2022-40897",
            "https://bugzilla.redhat.com/2158559",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2158559",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897",
            "https://errata.almalinux.org/9/ALSA-2023-0952.html",
            "https://errata.rockylinux.org/RLSA-2023:0952",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2022-43012.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
            "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
            "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
            "https://github.com/pypa/setuptools/issues/3659",
            "https://linux.oracle.com/cve/CVE-2022-40897.html",
            "https://linux.oracle.com/errata/ELSA-2024-2987.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
            "https://security.netapp.com/advisory/ntap-20230214-0001",
            "https://security.netapp.com/advisory/ntap-20230214-0001/",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://setuptools.pypa.io/en/latest",
            "https://ubuntu.com/security/notices/USN-5817-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-40897"
          ],
          "PublishedDate": "2022-12-23T00:15:13.987Z",
          "LastModifiedDate": "2024-11-21T07:22:13.787Z"
        },
        {
          "VulnerabilityID": "CVE-2024-6345",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-40.0.0-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@40.0.0",
            "UID": "40194c84ee4b8bf6"
          },
          "InstalledVersion": "40.0.0",
          "FixedVersion": "70.0.0",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-6345",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa/setuptools: Remote code execution via download functions in the package_index module in pypa/setuptools",
          "Description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-94"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:6726",
            "https://access.redhat.com/security/cve/CVE-2024-6345",
            "https://bugzilla.redhat.com/2297771",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2297771",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-6345",
            "https://errata.almalinux.org/9/ALSA-2024-6726.html",
            "https://errata.rockylinux.org/RLSA-2024:6726",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0",
            "https://github.com/pypa/setuptools/pull/4332",
            "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5",
            "https://linux.oracle.com/cve/CVE-2024-6345.html",
            "https://linux.oracle.com/errata/ELSA-2024-6726.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
            "https://ubuntu.com/security/notices/USN-7002-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-6345"
          ],
          "PublishedDate": "2024-07-15T01:15:01.73Z",
          "LastModifiedDate": "2024-11-21T09:49:28.17Z"
        },
        {
          "VulnerabilityID": "CVE-2025-47273",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-40.0.0-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@40.0.0",
            "UID": "40194c84ee4b8bf6"
          },
          "InstalledVersion": "40.0.0",
          "FixedVersion": "78.1.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47273",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "setuptools: Path Traversal Vulnerability in setuptools PackageIndex",
          "Description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
              "V3Score": 7.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:13578",
            "https://access.redhat.com/security/cve/CVE-2025-47273",
            "https://bugzilla.redhat.com/2366982",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2366982",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-47273",
            "https://errata.almalinux.org/9/ALSA-2025-13578.html",
            "https://errata.rockylinux.org/RLSA-2025:11036",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2025-49.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88",
            "https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b",
            "https://github.com/pypa/setuptools/issues/4946",
            "https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf",
            "https://linux.oracle.com/cve/CVE-2025-47273.html",
            "https://linux.oracle.com/errata/ELSA-2025-9940.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47273",
            "https://ubuntu.com/security/notices/USN-7544-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47273"
          ],
          "PublishedDate": "2025-05-17T16:15:19.11Z",
          "LastModifiedDate": "2025-06-12T16:29:01.66Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40898",
          "PkgName": "wheel",
          "PkgPath": "usr/local/lib/python2.7/site-packages/wheel-0.31.1-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/wheel@0.31.1",
            "UID": "6d6515f2a1fb53c3"
          },
          "InstalledVersion": "0.31.1",
          "FixedVersion": "0.38.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:54d52b0fdef297487119f71bdadd89eb8bb0770f1560987ecfcbfaa33612910e",
            "DiffID": "sha256:144f2ed1c39f1bbb7b6a4513694753770f0949475d1c4533d557c1124dca287b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40898",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
          "Description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:6712",
            "https://access.redhat.com/security/cve/CVE-2022-40898",
            "https://bugzilla.redhat.com/2165864",
            "https://errata.almalinux.org/9/ALSA-2023-6712.html",
            "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6",
            "https://github.com/pypa/advisory-database/tree/main/vulns/wheel/PYSEC-2022-43017.yaml",
            "https://github.com/pypa/wheel",
            "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
            "https://github.com/pypa/wheel/commit/88f02bc335d5404991e532e7f3b0fc80437bf4e0",
            "https://linux.oracle.com/cve/CVE-2022-40898.html",
            "https://linux.oracle.com/errata/ELSA-2023-6712.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
            "https://pypi.org/project/wheel",
            "https://pypi.org/project/wheel/",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40898/51499",
            "https://ubuntu.com/security/notices/USN-5821-1",
            "https://ubuntu.com/security/notices/USN-5821-2",
            "https://ubuntu.com/security/notices/USN-5821-3",
            "https://www.cve.org/CVERecord?id=CVE-2022-40898"
          ],
          "PublishedDate": "2022-12-23T00:15:14.043Z",
          "LastModifiedDate": "2025-04-15T16:15:19.237Z"
        }
      ],
      "vulnerability_count": 7
    },
    "2.9.10--hdfd78af_2": {
      "image": "ghcr.io/bundlecore/products/bfx/strelka2:2.9.10--hdfd78af_2",
      "vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2023-37920",
          "PkgName": "certifi",
          "PkgPath": "usr/local/lib/python2.7/site-packages/certifi-2019.11.28-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/certifi@2019.11.28",
            "UID": "d6dd3889bbb41743"
          },
          "InstalledVersion": "2019.11.28",
          "FixedVersion": "2023.7.22",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:9f987730c7d65572b326c5548a4be55ce6ddb05018334ab41d103854ba2497c0",
            "DiffID": "sha256:0a3785bad19101e90051f0c8595b0832754dee050c3b860749c7fb661fe2257f"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-37920",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: Removal of e-Tugra root certificate",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-345"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 4,
            "ghsa": 3,
            "nvd": 4,
            "oracle-oval": 2,
            "photon": 4,
            "redhat": 1
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:7753",
            "https://access.redhat.com/security/cve/CVE-2023-37920",
            "https://bugzilla.redhat.com/2226586",
            "https://bugzilla.redhat.com/2242493",
            "https://errata.almalinux.org/9/ALSA-2023-7753.html",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A",
            "https://linux.oracle.com/cve/CVE-2023-37920.html",
            "https://linux.oracle.com/errata/ELSA-2024-0133.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-37920",
            "https://security.netapp.com/advisory/ntap-20240912-0002",
            "https://security.netapp.com/advisory/ntap-20240912-0002/",
            "https://www.cve.org/CVERecord?id=CVE-2023-37920"
          ],
          "PublishedDate": "2023-07-25T21:15:10.827Z",
          "LastModifiedDate": "2025-02-13T13:50:15.813Z"
        },
        {
          "VulnerabilityID": "CVE-2021-3572",
          "PkgName": "pip",
          "PkgPath": "usr/local/site-packages/pip-20.1.1-py3.6.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@20.1.1",
            "UID": "830e1a9ee1d6c002"
          },
          "InstalledVersion": "20.1.1",
          "FixedVersion": "21.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:9f987730c7d65572b326c5548a4be55ce6ddb05018334ab41d103854ba2497c0",
            "DiffID": "sha256:0a3785bad19101e90051f0c8595b0832754dee050c3b860749c7fb661fe2257f"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3572",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pip: Incorrect handling of unicode separators in git references",
          "Description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 1,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 3,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V2Score": 3.5,
              "V3Score": 5.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 4.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2021:3254",
            "https://access.redhat.com/security/cve/CVE-2021-3572",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1962856",
            "https://github.com/advisories/GHSA-5xp3-jfq3-5q8x",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2021-437.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b",
            "https://github.com/pypa/pip/issues/10042",
            "https://github.com/pypa/pip/issues/10042#issuecomment-857452480",
            "https://github.com/pypa/pip/pull/9827",
            "https://github.com/skazi0/CVE-2021-3572/blob/master/CVE-2021-3572-v9.0.1.patch",
            "https://linux.oracle.com/cve/CVE-2021-3572.html",
            "https://linux.oracle.com/errata/ELSA-2023-12349.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-3572",
            "https://packetstormsecurity.com/files/162712/USN-4961-1.txt",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://ubuntu.com/security/notices/USN-4961-2",
            "https://www.cve.org/CVERecord?id=CVE-2021-3572",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-11-10T18:15:09.51Z",
          "LastModifiedDate": "2024-11-21T06:21:52.473Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40897",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-44.0.0.post20200102-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@44.0.0.post20200102",
            "UID": "33cd9a1b4aa1477a"
          },
          "InstalledVersion": "44.0.0.post20200102",
          "FixedVersion": "65.5.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:9f987730c7d65572b326c5548a4be55ce6ddb05018334ab41d103854ba2497c0",
            "DiffID": "sha256:0a3785bad19101e90051f0c8595b0832754dee050c3b860749c7fb661fe2257f"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40897",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
          "Description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-1333"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:0952",
            "https://access.redhat.com/security/cve/CVE-2022-40897",
            "https://bugzilla.redhat.com/2158559",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2158559",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897",
            "https://errata.almalinux.org/9/ALSA-2023-0952.html",
            "https://errata.rockylinux.org/RLSA-2023:0952",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2022-43012.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
            "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
            "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
            "https://github.com/pypa/setuptools/issues/3659",
            "https://linux.oracle.com/cve/CVE-2022-40897.html",
            "https://linux.oracle.com/errata/ELSA-2024-2987.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
            "https://security.netapp.com/advisory/ntap-20230214-0001",
            "https://security.netapp.com/advisory/ntap-20230214-0001/",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://setuptools.pypa.io/en/latest",
            "https://ubuntu.com/security/notices/USN-5817-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-40897"
          ],
          "PublishedDate": "2022-12-23T00:15:13.987Z",
          "LastModifiedDate": "2024-11-21T07:22:13.787Z"
        },
        {
          "VulnerabilityID": "CVE-2024-6345",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-44.0.0.post20200102-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@44.0.0.post20200102",
            "UID": "33cd9a1b4aa1477a"
          },
          "InstalledVersion": "44.0.0.post20200102",
          "FixedVersion": "70.0.0",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:9f987730c7d65572b326c5548a4be55ce6ddb05018334ab41d103854ba2497c0",
            "DiffID": "sha256:0a3785bad19101e90051f0c8595b0832754dee050c3b860749c7fb661fe2257f"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-6345",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa/setuptools: Remote code execution via download functions in the package_index module in pypa/setuptools",
          "Description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-94"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:6726",
            "https://access.redhat.com/security/cve/CVE-2024-6345",
            "https://bugzilla.redhat.com/2297771",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2297771",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-6345",
            "https://errata.almalinux.org/9/ALSA-2024-6726.html",
            "https://errata.rockylinux.org/RLSA-2024:6726",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0",
            "https://github.com/pypa/setuptools/pull/4332",
            "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5",
            "https://linux.oracle.com/cve/CVE-2024-6345.html",
            "https://linux.oracle.com/errata/ELSA-2024-6726.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
            "https://ubuntu.com/security/notices/USN-7002-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-6345"
          ],
          "PublishedDate": "2024-07-15T01:15:01.73Z",
          "LastModifiedDate": "2024-11-21T09:49:28.17Z"
        },
        {
          "VulnerabilityID": "CVE-2025-47273",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/site-packages/setuptools-44.0.0.post20200102-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@44.0.0.post20200102",
            "UID": "33cd9a1b4aa1477a"
          },
          "InstalledVersion": "44.0.0.post20200102",
          "FixedVersion": "78.1.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:9f987730c7d65572b326c5548a4be55ce6ddb05018334ab41d103854ba2497c0",
            "DiffID": "sha256:0a3785bad19101e90051f0c8595b0832754dee050c3b860749c7fb661fe2257f"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47273",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "setuptools: Path Traversal Vulnerability in setuptools PackageIndex",
          "Description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
              "V3Score": 7.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:13578",
            "https://access.redhat.com/security/cve/CVE-2025-47273",
            "https://bugzilla.redhat.com/2366982",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2366982",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-47273",
            "https://errata.almalinux.org/9/ALSA-2025-13578.html",
            "https://errata.rockylinux.org/RLSA-2025:11036",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2025-49.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88",
            "https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b",
            "https://github.com/pypa/setuptools/issues/4946",
            "https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf",
            "https://linux.oracle.com/cve/CVE-2025-47273.html",
            "https://linux.oracle.com/errata/ELSA-2025-9940.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47273",
            "https://ubuntu.com/security/notices/USN-7544-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47273"
          ],
          "PublishedDate": "2025-05-17T16:15:19.11Z",
          "LastModifiedDate": "2025-06-12T16:29:01.66Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40898",
          "PkgName": "wheel",
          "PkgPath": "usr/local/lib/python2.7/site-packages/wheel-0.37.1-py3.8.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/wheel@0.37.1",
            "UID": "1f053c5cf181c1e4"
          },
          "InstalledVersion": "0.37.1",
          "FixedVersion": "0.38.1",
          "Status": "fixed",
          "Layer": {
            "Digest": "sha256:9f987730c7d65572b326c5548a4be55ce6ddb05018334ab41d103854ba2497c0",
            "DiffID": "sha256:0a3785bad19101e90051f0c8595b0832754dee050c3b860749c7fb661fe2257f"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40898",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
          "Description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:6712",
            "https://access.redhat.com/security/cve/CVE-2022-40898",
            "https://bugzilla.redhat.com/2165864",
            "https://errata.almalinux.org/9/ALSA-2023-6712.html",
            "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6",
            "https://github.com/pypa/advisory-database/tree/main/vulns/wheel/PYSEC-2022-43017.yaml",
            "https://github.com/pypa/wheel",
            "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
            "https://github.com/pypa/wheel/commit/88f02bc335d5404991e532e7f3b0fc80437bf4e0",
            "https://linux.oracle.com/cve/CVE-2022-40898.html",
            "https://linux.oracle.com/errata/ELSA-2023-6712.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
            "https://pypi.org/project/wheel",
            "https://pypi.org/project/wheel/",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40898/51499",
            "https://ubuntu.com/security/notices/USN-5821-1",
            "https://ubuntu.com/security/notices/USN-5821-2",
            "https://ubuntu.com/security/notices/USN-5821-3",
            "https://www.cve.org/CVERecord?id=CVE-2022-40898"
          ],
          "PublishedDate": "2022-12-23T00:15:14.043Z",
          "LastModifiedDate": "2025-04-15T16:15:19.237Z"
        }
      ],
      "vulnerability_count": 6
    }
  },
  "summary": {
    "total_versions_scanned": 3,
    "total_vulnerabilities": 20
  }
}
